# Site settings
title: 本天堂 - 本本子的个人博客
description: '欢迎来逛一逛哦' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://benbenzi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/Bentendo.pngg"
logo-icon: "/assets/img/branding/Bentendo-symbol.png"
logo-icon-SEO: "/assets/img/branding/Bentendo-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/Bentendo-dark.png"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: 本本子 # add your name
author-pic: Myself_Neon_grey.jpg
about-author: 咸鱼肥宅一条。虽然学的是开发，但目前还是随着自己的喜好，做着游戏自媒体工作。平时主要都是主机游戏，以任天堂为主。这个博客主要就是用于记录自己的一些日常或者随笔。

# Contact links
email: flamebeam0131@gmail.com # Add your Email address
phone: # Add your Phone number
website: https://benbenzi.github.io # Add your website
linkedin: amaynez # Add your Linkedin handle
github: https://github.com/benbenzi
twitter: '@flamebeam0131' # Add your Twitter handle
bandcamp: armandomaynez # Add your Bandcamp username

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Disqus
discus_identifier: amaynez-github-io # Add your discus identifier
comments_curtain: yes # leave empty to show the disqus embed directly

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]